-- Create bulk_payment table
CREATE TABLE IF NOT EXISTS `bulk_payment` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `qr_image` VARCHAR(500) DEFAULT NULL,
  `qr_name` VARCHAR(255) DEFAULT NULL,
  `is_active` TINYINT(1) DEFAULT 1,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
